version: '3.8'
services:
  pagerduty-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PAGERDUTY_API_TOKEN=${PAGERDUTY_API_TOKEN}
      - PAGERDUTY_API_URL=${PAGERDUTY_API_URL}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pagerduty
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - pagerduty-app
volumes:
  mysqldata:
